#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '<u><i> {{ path .Path .Location }}</i></u>'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'green'
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}',
      '{{ if gt .Ahead 0 }}#49416D{{ end }}',
      '{{ if gt .Behind 0 }}#7A306C{{ end }}'
    ]
    template = """\
     {{ if .UpstreamURL }} • {{ url .UpstreamIcon .UpstreamURL }}{{ end }}\
     {{ .HEAD }}\
     {{if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
     {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
     {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
    """

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'white'
    background = 'transparent'
    template = '<blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = 'white'
    background = 'transparent'
    template = " <#fefefe></> {{ .FormattedMs }} "
    [blocks.segments.properties]
    threshold = 5000
    style = "austin"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}red{{else}}green{{end}}']
    background = 'transparent'
    template = '{{ if gt .Code 0 }}{{ else }}{{ end }} ⟫'
    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = "command"
    style = "plain"
    foreground = 'white'
    background = 'transparent'
    [blocks.segments.properties]
    shell = "bash"
    command = "df -H /dev/sdc | awk 'NR >= 2 {print  \"🖴 : \" $5}'"

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#94ffa2'
    template = ' <#ffffff>▤ :</> {{ round .PhysicalPercentUsed .Precision }}% ({{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB)'

[transient_prompt]
  foreground = 'white'
  background = 'transparent'
  template = '<u>{{ now | date "15:04:05" }}</u> → '

[secondary_prompt]
  foreground = 'white'
  background = 'transparent'
  template = '<yellow,transparent></><,yellow> > </><yellow,transparent></> '



[[tooltips]]
  type = "kubectl"
  tips = ["k", "kubectl"]
  style = "plain"
  foreground = "green"
  template = "ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"
  [tooltips.properties]
    parse_kubeconfig = true
